### ISSUE TITLE
Error: out-of-sync-migrations or _actual_app_crdt__WEBPACK_IMPORTED_MODULE_0__ is undefined

### ISSUE THREAD

**Issue by xplreitr** [youngcw/actual_mint_importer#11]
Using Actual Budget Client version: v23.12.0, Server version: v23.12.1 via docker.

I attempted running the import in an empty budget file and a partially filled budget file. They all returned the same error. 

ran `docker build -t actual_mint_importer https://github.com/youngcw/actual_mint_importer.git`

ran ` docker run -e ACTUAL_SERVER_PASSWORD=longpassword -e ACTUAL_SYNC_ID=d8c319...8c716e6b -e ACTUAL_SERVER_URL=https://actual.example.com -e IMPORTER_CACHE_DIR=./cache -v ./transactions.csv:/data/transactions.csv actual_mint_importer`

It returned the following: 
```
[                                                      
  'Account 1',
  'Account 2',
  '...',
  'Account 35'
]
[
  'Category 1',           'Category 2',   'Category 3',
  'Category 4',             '...',             'Category 99'
]
open file
connect
Database is out of sync with migrations: {
  appliedIds: [
    1548957970627, 1550601598648,
    1555786194328, 1561751833510,
    1567699552727, 1582384163573,
    1597756566448, 1608652596043,
    1608652596044, 1612625548236,
    1614782639336, 1615745967948,
    1616167010796, 1618975177358,
    1632571489012, 1679728867040,
    1681115033845, 1682974838138,
    1685007876842, 1686139660866,
    1688749527273, 1688841238000,
    1691233396000, 1694438752000,
    1697046240000
  ],
  available: [
    '1548957970627_remove-db-version.sql',
    '1550601598648_payees.sql',
    '1555786194328_remove_category_group_unique.sql',
    '1561751833510_indexes.sql',
    '1567699552727_budget.sql',
    '1582384163573_cleared.sql',
    '1597756566448_rules.sql',
    '1608652596043_parent_field.sql',
    '1608652596044_trans_views.sql',
    '1612625548236_optimize.sql',
    '1614782639336_trans_views2.sql',
    '1615745967948_meta.sql',
    '1616167010796_accounts_order.sql',
    '1618975177358_schedules.sql',
    '1632571489012_remove_cache.js',
    '1679728867040_rules_conditions.sql',
    '1681115033845_add_schedule_name.sql',
    '1682974838138_remove_payee_rules.sql',
    '1685007876842_add_category_hidden.sql',
    '1686139660866_remove_account_type.sql',
    '1688749527273_transaction_filters.sql',
    '1688841238000_add_account_type.sql',
    '1691233396000_add_schedule_next_date_tombstone.sql'
  ]
}
Error updating Error: out-of-sync-migrations
    at checkDatabaseValidity (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40813:31)
    at Module.migrate (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40821:17)
    at async runMigrations (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44260:17)
    at async updateVersion (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44274:17)
    at async loadBudget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40433:21)
    at async handlers.load-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40274:27)
    at async handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40244:17)
    at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32098:34)
TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43625:96)
    at /app/node_modules/@actual-app/api/dist/app/bundle.api.js:43537:38
    at onceFn (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44451:35)
    at initialFullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43523:36)
    at handlers.sync-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40259:92)
    at handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40247:55)
    at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32098:34)
[Exception] TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43625:96)
    at /app/node_modules/@actual-app/api/dist/app/bundle.api.js:43537:38
    at onceFn (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44451:35)
    at initialFullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43523:36)
    at handlers.sync-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40259:92)
    at handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:40247:55)
    at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32098:34)
Full error details {
  message: "Cannot read properties of undefined (reading 'timestamp')",
  reason: undefined,
  meta: undefined
}
/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32103
                        throw new Error((0, _shared_errors__WEBPACK_IMPORTED_MODULE_2__.getDownloadError)(result.error));
                              ^

Error: Something went wrong trying to download that file, sorry! Visit https://actualbudget.org/contact/ for support. (reason: undefined)
    at handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32103:31)

Node.js v21.4.0
```
 
Let me know what other information might be useful.

**Comment by youngcw** [comment]
Make sure you are using the Actual API version 6.3.0. My guess is that you are on 6.2.1 still

**Comment by xplreitr** [comment]
Thanks for pointing me in the right direction. I tried to put the changes in for future mint refugees. I hope I managed correctly.

**Comment by Snuupy** [comment]
just a fyi now needs to be v6.5.0 and in the future can be found at https://github.com/actualbudget/actual/blob/master/packages/api/package.json

**Comment by boilermaker-ben** [comment]
Thanks for creating this tool, [youngcw](https://github.com/youngcw). However, I'm dealing with the same issue as posted by [xplreitr](https://github.com/xplreitr). 

I recently updated to the newest version of Actual Budget (docker) to version 24.2.0 before trying this, which seems to have been a mistake. Seeing the same type of error:

```
[                                                      
  'Account 1',
  'Account 2',
  '...',
  'Account 35'
]
[
  'Category 1',
  'Category 2',
  'Category 3',
  'Category 4', 
  '...' ,
  'Category 99'
]
open file
connect
Database is out of sync with migrations: {
  appliedIds: [
    1548957970627, 1550601598648,
    1555786194328, 1561751833510,
    1567699552727, 1582384163573,
    1597756566448, 1608652596043,
    1608652596044, 1612625548236,
    1614782639336, 1615745967948,
    1616167010796, 1618975177358,
    1632571489012, 1679728867040,
    1681115033845, 1682974838138,
    1685007876842, 1686139660866,
    1688749527273, 1688841238000,
    1691233396000, 1694438752000,
    1697046240000, 1704572023730,
    1704572023731
  ],
  available: [
    '1548957970627_remove-db-version.sql',
    '1550601598648_payees.sql',
    '1555786194328_remove_category_group_unique.sql',
    '1561751833510_indexes.sql',
    '1567699552727_budget.sql',
    '1582384163573_cleared.sql',
    '1597756566448_rules.sql',
    '1608652596043_parent_field.sql',
    '1608652596044_trans_views.sql',
    '1612625548236_optimize.sql',
    '1614782639336_trans_views2.sql',
    '1615745967948_meta.sql',
    '1616167010796_accounts_order.sql',
    '1618975177358_schedules.sql',
    '1632571489012_remove_cache.js',
    '1679728867040_rules_conditions.sql',
    '1681115033845_add_schedule_name.sql',
    '1682974838138_remove_payee_rules.sql',
    '1685007876842_add_category_hidden.sql',
    '1686139660866_remove_account_type.sql',
    '1688749527273_transaction_filters.sql',
    '1688841238000_add_account_type.sql',
    '1691233396000_add_schedule_next_date_tombstone.sql',
    '1694438752000_add_goal_targets.sql',
    '1697046240000_add_reconciled.sql'
  ]
}
Error updating Error: out-of-sync-migrations
    at checkDatabaseValidity (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44308:31)
    at Module.migrate (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44316:17)
    at async runMigrations (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:48024:17)
    at async updateVersion (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:48043:17)
    at async loadBudget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43914:21)
    at async handlers.load-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43744:27)
    at async handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43714:17)
    at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:34861:34)
TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47369:96)
    at /app/node_modules/@actual-app/api/dist/app/bundle.api.js:47281:38
    at onceFn (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:48220:35)
    at initialFullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47267:36)
    at handlers.sync-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43729:92)
    at handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43717:55)
    at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:34861:34)
[Exception] TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47369:96)
    at /app/node_modules/@actual-app/api/dist/app/bundle.api.js:47281:38
    at onceFn (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:48220:35)
    at initialFullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47267:36)
    at handlers.sync-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43729:92)
    at handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:43717:55)
    at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:34861:34)
Full error details {
  message: "Cannot read properties of undefined (reading 'timestamp')",
  reason: undefined,
  meta: undefined
}
/app/node_modules/@actual-app/api/dist/app/bundle.api.js:34866
                        throw new Error((0, _shared_errors__WEBPACK_IMPORTED_MODULE_2__.getDownloadError)(result.error));
                              ^

Error: Something went wrong trying to download that file, sorry! Visit https://actualbudget.org/contact/ for support. (reason: undefined)
    at handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:34866:31)

Node.js v21.6.2
```

**Comment by youngcw** [comment]
@boilermaker-ben you need to update your api version

**Comment by boilermaker-ben** [comment]
Thanks for the speedy response. Pardon my ignorance, but I'm not sure how to update the API. I had assumed I was already moved to the v6.5.0 by doing an Actual Budget pull (docker-compose pull). Do I need to install the API separately or run it through a different docker container? At the moment, the "/data" directory is the only volume mapped via docker-compose.

**Comment by youngcw** [comment]
@boilermaker-ben You need to update the api version used by this project.  You can run `npm update` to do it

**Comment by youngcw** [comment]
@boilermaker-ben I updated things so you should be good now if you pull down the updates

**Comment by boilermaker-ben** [comment]
> @boilermaker-ben I updated things so you should be good now if you pull down the updates

I had been trying with the docker image I built. Worked fine with the cloned repo and running the script. Thanks for looking into it and your hard work to make it.

**Comment by badabing2005** [comment]
I'm running into the same issue with the latest docker code.
Followed the instructions.
"@actual-app/api": "^6.7.0"

**Comment by Snuupy** [comment]
> I'm running into the same issue with the latest docker code. Followed the instructions. "@actual-app/api": "^6.7.0"

after you change the version number you need to run `npm i` so dependencies will update. Or in docker, you will have to probably `docker exec -it container_name /bin/bash` (or `/bin/sh`), `cd` to the app dir (wherever that is in the container), and `npm i` Then try again. I did not try the container myself, I just ran it locally with node version manager (nvm).

P.S. love the work you do on PixelFlasher!

Edit: also I should warn you that when I imported a large number of transactions (16k+) some failed and there is no retry loop yet so some transactions may not get imported (but unless you save all the output logs it's hard to tell which ones failed). User beware.

**Comment by badabing2005** [comment]
> > I'm running into the same issue with the latest docker code. Followed the instructions. "@actual-app/api": "^6.7.0"
> 
> after you change the version number you need to run `npm i` so dependencies will update. Or in docker, you will have to probably `docker exec -it container_name /bin/bash` (or `/bin/sh`), `cd` to the app dir (wherever that is in the container), and `npm i` Then try again. I did not try the container myself, I just ran it locally with node version manager (nvm).
> 
> P.S. love the work you do on PixelFlasher!
> 
> Edit: also I should warn you that when I imported a large number of transactions (16k+) some failed and there is no retry loop yet so some transactions may not get imported (but unless you save all the output logs it's hard to tell which ones failed). User beware.

Thanks for the quick response and PixelFlasher mention :)
Container is not running, it quits immediately, so no docker exec.
I didn't change any version, started with the latest, and it already has it set to 6.7
I build it as instructed and then simple run.

The transactions.csv I'm using to test is:
```
"Date","Description","Original Description","Amount","Transaction Type","Category","Account Name","Labels","Notes"
"3/22/2024","CASH INTEREST","CASH INTEREST","0.21","debit","Finance Charge","From C1","",""
```

And I get the following error.
```
[+] Building 0.6s (16/16) FINISHED                                                                                                                                                                 docker:default
 => [actual_mint_importer internal] load build definition from Dockerfile                                                                                                                                    0.0s
 => => transferring dockerfile: 435B                                                                                                                                                                         0.0s
 => [actual_mint_importer internal] load metadata for docker.io/library/node:21-bookworm-slim                                                                                                                0.5s
 => [actual_mint_importer internal] load metadata for docker.io/library/node:21-bookworm                                                                                                                     0.5s
 => [actual_mint_importer internal] load .dockerignore                                                                                                                                                       0.0s
 => => transferring context: 62B                                                                                                                                                                             0.0s
 => [actual_mint_importer build 1/5] FROM docker.io/library/node:21-bookworm@sha256:bda531283f4bafd1cb41294493de89ae3c4cf55933da14710e46df970e77365e                                                         0.0s
 => [actual_mint_importer stage-1 1/5] FROM docker.io/library/node:21-bookworm-slim@sha256:db308384dbc89ee55e0a6d04279a351277b2cff03c18556c347517e4a7dee470                                                  0.0s
 => [actual_mint_importer internal] load build context                                                                                                                                                       0.0s
 => => transferring context: 98B                                                                                                                                                                             0.0s
 => CACHED [actual_mint_importer stage-1 2/5] WORKDIR /app                                                                                                                                                   0.0s
 => CACHED [actual_mint_importer build 2/5] RUN apt-get update && apt-get install -y openssl                                                                                                                 0.0s
 => CACHED [actual_mint_importer build 3/5] COPY package.json package-lock.json ./app/                                                                                                                       0.0s
 => CACHED [actual_mint_importer build 4/5] WORKDIR /app                                                                                                                                                     0.0s
 => CACHED [actual_mint_importer build 5/5] RUN npm install                                                                                                                                                  0.0s
 => CACHED [actual_mint_importer stage-1 3/5] COPY --from=build /app /app                                                                                                                                    0.0s
 => CACHED [actual_mint_importer stage-1 4/5] COPY mint.js ./                                                                                                                                                0.0s
 => CACHED [actual_mint_importer stage-1 5/5] RUN mkdir /data ./cache                                                                                                                                        0.0s
 => [actual_mint_importer] exporting to image                                                                                                                                                                0.0s
 => => exporting layers                                                                                                                                                                                      0.0s
 => => writing image sha256:19335947851a13cebb85d063c8477accb47f120328d3ecdd52edcb494ebb258c                                                                                                                 0.0s
 => => naming to docker.io/library/actual_mint_importer-actual_mint_importer                                                                                                                                 0.0s
[+] Running 1/1
 ✔ Container actual_mint_importer  Started                                                                                                                                                                   0.1s
actual_mint_importer  | [ 'From C1' ]
actual_mint_importer  | [ 'Finance Charge' ]
actual_mint_importer  | open file
actual_mint_importer  | connect
actual_mint_importer  | Database is out of sync with migrations: {
actual_mint_importer  |   appliedIds: [
actual_mint_importer  |     1548957970627, 1550601598648,
actual_mint_importer  |     1555786194328, 1561751833510,
actual_mint_importer  |     1567699552727, 1582384163573,
actual_mint_importer  |     1597756566448, 1608652596043,
actual_mint_importer  |     1608652596044, 1612625548236,
actual_mint_importer  |     1614782639336, 1615745967948,
actual_mint_importer  |     1616167010796, 1618975177358,
actual_mint_importer  |     1632571489012, 1679728867040,
actual_mint_importer  |     1681115033845, 1682974838138,
actual_mint_importer  |     1685007876842, 1686139660866,
actual_mint_importer  |     1688749527273, 1688841238000,
actual_mint_importer  |     1691233396000, 1694438752000,
actual_mint_importer  |     1697046240000, 1704572023730,
actual_mint_importer  |     1704572023731, 1707267033000,
actual_mint_importer  |     1712784523000
actual_mint_importer  |   ],
actual_mint_importer  |   available: [
actual_mint_importer  |     '1548957970627_remove-db-version.sql',
actual_mint_importer  |     '1550601598648_payees.sql',
actual_mint_importer  |     '1555786194328_remove_category_group_unique.sql',
actual_mint_importer  |     '1561751833510_indexes.sql',
actual_mint_importer  |     '1567699552727_budget.sql',
actual_mint_importer  |     '1582384163573_cleared.sql',
actual_mint_importer  |     '1597756566448_rules.sql',
actual_mint_importer  |     '1608652596043_parent_field.sql',
actual_mint_importer  |     '1608652596044_trans_views.sql',
actual_mint_importer  |     '1612625548236_optimize.sql',
actual_mint_importer  |     '1614782639336_trans_views2.sql',
actual_mint_importer  |     '1615745967948_meta.sql',
actual_mint_importer  |     '1616167010796_accounts_order.sql',
actual_mint_importer  |     '1618975177358_schedules.sql',
actual_mint_importer  |     '1632571489012_remove_cache.js',
actual_mint_importer  |     '1679728867040_rules_conditions.sql',
actual_mint_importer  |     '1681115033845_add_schedule_name.sql',
actual_mint_importer  |     '1682974838138_remove_payee_rules.sql',
actual_mint_importer  |     '1685007876842_add_category_hidden.sql',
actual_mint_importer  |     '1686139660866_remove_account_type.sql',
actual_mint_importer  |     '1688749527273_transaction_filters.sql',
actual_mint_importer  |     '1688841238000_add_account_type.sql',
actual_mint_importer  |     '1691233396000_add_schedule_next_date_tombstone.sql',
actual_mint_importer  |     '1694438752000_add_goal_targets.sql',
actual_mint_importer  |     '1697046240000_add_reconciled.sql',
actual_mint_importer  |     '1704572023730_add_account_sync_source.sql',
actual_mint_importer  |     '1704572023731_add_missing_goCardless_sync_source.sql',
actual_mint_importer  |     '1707267033000_reports.sql'
actual_mint_importer  |   ]
actual_mint_importer  | }
actual_mint_importer  | Error updating Error: out-of-sync-migrations
actual_mint_importer  |     at checkDatabaseValidity (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44738:31)
actual_mint_importer  |     at Module.migrate (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44746:17)
actual_mint_importer  |     at async runMigrations (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:48546:17)
actual_mint_importer  |     at async updateVersion (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:48565:17)
actual_mint_importer  |     at async loadBudget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44354:21)
actual_mint_importer  |     at async handlers.load-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44184:29)
actual_mint_importer  |     at async handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44154:17)
actual_mint_importer  |     at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:35065:36)
actual_mint_importer  | TypeError: Cannot read properties of undefined (reading 'timestamp')
actual_mint_importer  |     at _fullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47889:98)
actual_mint_importer  |     at /app/node_modules/@actual-app/api/dist/app/bundle.api.js:47801:38
actual_mint_importer  |     at /app/node_modules/@actual-app/api/dist/app/bundle.api.js:48743:38
actual_mint_importer  |     at initialFullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47787:38)
actual_mint_importer  |     at handlers.sync-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44169:94)
actual_mint_importer  |     at handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44157:55)
actual_mint_importer  |     at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:35065:36)
actual_mint_importer  | [Exception] TypeError: Cannot read properties of undefined (reading 'timestamp')
actual_mint_importer  |     at _fullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47889:98)
actual_mint_importer  |     at /app/node_modules/@actual-app/api/dist/app/bundle.api.js:47801:38
actual_mint_importer  |     at /app/node_modules/@actual-app/api/dist/app/bundle.api.js:48743:38
actual_mint_importer  |     at initialFullSync (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:47787:38)
actual_mint_importer  |     at handlers.sync-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44169:94)
actual_mint_importer  |     at handlers.download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:44157:55)
actual_mint_importer  |     at async handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:35065:36)
actual_mint_importer  | Full error details {
actual_mint_importer  |   message: "Cannot read properties of undefined (reading 'timestamp')",
actual_mint_importer  |   reason: undefined,
actual_mint_importer  |   meta: undefined
actual_mint_importer  | }
actual_mint_importer  | /app/node_modules/@actual-app/api/dist/app/bundle.api.js:35070
actual_mint_importer  |                         throw new Error((0, _shared_errors__WEBPACK_IMPORTED_MODULE_2__.getDownloadError)(result.error));
actual_mint_importer  |                               ^
actual_mint_importer  |
actual_mint_importer  |
actual_mint_importer  | Error: Something went wrong trying to download that file, sorry! Visit https://actualbudget.org/contact/ for support. (reason: undefined)
actual_mint_importer  |     at handlers.api/download-budget (/app/node_modules/@actual-app/api/dist/app/bundle.api.js:35070:31)
actual_mint_importer  |
actual_mint_importer  |
actual_mint_importer  | Node.js v21.7.3
actual_mint_importer exited with code 1
```

**Comment by Snuupy** [comment]
yeah @badabing2005 don't use the docker container, the errors were opaque to me (and didn't work when I tried it). I only ever got the node version working when I tried (and that still needed manual edits to the script). If you don't mind polluting your system install with either node or node version manager.

**Comment by youngcw** [comment]
all the migration errors come from api/server version miss match.  I updated it so it should work now

**Comment by badabing2005** [comment]
Thank you @youngcw 
Works perfect.
